version: '3.2'

services:
  syslog:
    build:
      context: rsyslog/
    ports:
      - 514:514/tcp
      - 514:514/udp
    volumes:
      - ./logs:/var/log
      - ./rsyslog/rsyslog.d:/etc/rsyslog.d
      - ./rsyslog/conf/rsyslog.conf:/etc/rsyslog.conf
      - /Users/artemme/app/kafka_2.13-2.7.0:/etc/kafka
    networks:
      - elk_default

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
    networks:
      - elk_default

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.25.150:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_PLAINTEXT: INSIDE,OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logstash_logs:1:1"
    depends_on:
      - zookeeper
    container_name: kafka
    networks:
      - elk_default
    extra_hosts:
      - "host.docker.internal:192.168.25.150"  # Thay đổi IP này nếu cần

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - ./logs:/var/logstash/logs
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_default

networks:
  elk_default:
    external: true
